# Generated by Django 5.1.3 on 2024-12-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDetails',
            fields=[
                ('access_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('app', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('server_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('emp_key', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('updated_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('server_key', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('server_url', models.URLField()),
                ('app', models.CharField(max_length=255)),
                ('updated_time', models.DateField()),
            ],
        ),
    ]
