# Generated by Django 5.1.4 on 2025-06-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='user_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='accessdetails',
            table='access_details',
        ),
        migrations.AlterModelTable(
            name='employeedetails',
            table='employee_details',
        ),
        migrations.AlterModelTable(
            name='serverdetails',
            table='server_details',
        ),
    ]
