# Generated by Django 5.1.4 on 2025-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orionapp', '0003_alter_accessdetails_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='user_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
